### ISSUE TITLE
Could you provide some instructions on how to load this project into Pharo?

### ISSUE THREAD

**Issue by olekscode** [nikhilpinnaparaju/Pharo-Implementations#1]
In fact, I don't understand how you created this repository? It doesn't seem like you've been using Iceberg. 

PS. It would be good if you could describe in README how this project can be loaded

**Comment by nikhilpinnaparaju** [comment]
I was facing issues with Iceberg as I was behind a college proxy server and was unsure with how to get around it. Instead I used the monticello browser (reference - https://ci.inria.fr/pharo-contribution/job/UpdatedPharoByExample/lastSuccessfulBuild/artifact/book-result/SharingCode/SharingCode.html).
